# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-14 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
